Am adaugat chestii destul de importante
ZmoleCristian/TRAG pull request #2
Opened 2024-08-24 22:20 UTC by ZakkyPatronu

2024-08-24 23:46 UTC, ZmoleCristian commented on .config/alacritty/alacritty.toml
> +import = ["/home/zakky/.config/alacritty/themes/themes/vapor.toml"]
hardcode = bad

2024-08-24 23:48 UTC, ZmoleCristian commented on .zshrc
> +#prompt_user="%F{white}%K{blue}🥷 Andrei Veneticu-Cercel%f%k"
scos

2024-08-24 23:50 UTC, ZmoleCristian commented on .zshrc
> +prompt_user="%F{white}%K{blue}  Zakky %f%k"
dinamic

2024-08-24 23:51 UTC, ZmoleCristian requested changes
plz change

2024-08-25 00:08 UTC, ZakkyPatronu reviewed
gata man

2024-08-25 00:08 UTC, ZakkyPatronu commented on .zshrc
> +#prompt_user="%F{white}%K{blue}🥷 Andrei Veneticu-Cercel%f%k"
am scos

2024-08-25 21:39 UTC, ZmoleCristian approved these changes
multumesc

2024-08-25 21:39 UTC, merged